apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}-depl
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "frontend.fullname" . }}-app
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.repoTag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ include "frontend.fullname" . }}
        ports:
        - name: http
          containerPort: {{ .Values.spec.containerPort }}
        env:
        - name: BACKEND_URI
          valueFrom:
            configMapKeyRef:
              name: {{ include "frontend.fullname" . }}-config
              key: backend-uri
        - name: GUESTBOOK_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "frontend.fullname" . }}-config
              key: guestbook-name
