apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "frontend.fullname" . }}-svc
          servicePort: 80
