apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "frontend.fullname" . }}
  name: {{ include "frontend.fullname" . }}-svc
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  ports:
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: 4200
  {{- end }}
  selector:
    app: {{ include "frontend.fullname" . }}-app
